# -*- coding: utf-8 -*-
"""Código do Dashboard do Dólar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w5-TQGrheVUzRrt4M12E8eDgPm75nO7e
"""

# dashboard_dolar.py

import streamlit as st
import pandas as pd
import yfinance as yf
import plotly.express as px
from datetime import datetime

# --- 1. Configurações da Página ---
st.set_page_config(
    layout="wide",
    page_title="Dashboard Histórico do Dólar",
    page_icon="💵"
)

# --- 2. Título e Introdução ---
st.title("📈 Dashboard Histórico: O Dólar nos Últimos 10 Anos")
st.markdown("""
Esta visualização interativa mostra a trajetória da cotação do **Dólar (USD)** em relação ao **Real (BRL)** desde junho de 2015.
Passe o mouse sobre o gráfico para ver os valores e use os botões para navegar. As linhas verticais marcam eventos cruciais que impactaram a economia brasileira.
""")

# --- 3. Carregamento e Cache dos Dados ---
@st.cache_data
def carregar_dados(data_inicio, data_fim):
    try:
        dados = yf.download('BRL=X', start=data_inicio, end=data_fim, auto_adjust=True)
        if dados.empty:
            st.warning("Não foram encontrados dados para o período selecionado. Verifique a conexão com a internet.")
            return pd.DataFrame()
        dados_limpos = pd.DataFrame()
        dados_limpos['Cotação'] = dados['Close']  # Garante que é 1D
        dados_limpos.index.name = 'Date'  # Nomeia o índice para manter consistência
        return dados_limpos
    except Exception as e:
        st.error(f"Ocorreu um erro ao buscar os dados no Yahoo Finance: {e}")
        return pd.DataFrame()

data_inicio = '2015-06-01'
data_fim = datetime.now().strftime('%Y-%m-%d')
dados_dolar = carregar_dados(data_inicio, data_fim)

# --- 4. Criação do Gráfico (se os dados foram carregados) ---
if not dados_dolar.empty:
    eventos = [
        {'data': '2016-08-31', 'evento': 'Impeachment de Dilma Rousseff', 'posicao_y': 3.5},
        {'data': '2018-05-21', 'evento': 'Greve dos Caminhoneiros', 'posicao_y': 3.8},
        {'data': '2020-03-11', 'evento': 'OMS declara pandemia de COVID-19', 'posicao_y': 5.0},
        {'data': '2020-05-18', 'evento': 'Pico do Dólar (Pandemia)', 'posicao_y': 5.95},
        {'data': '2021-01-01', 'evento': 'Início do ciclo de alta da inflação', 'posicao_y': 5.5},
        {'data': '2022-02-24', 'evento': 'Início da Guerra na Ucrânia', 'posicao_y': 4.9},
        {'data': '2022-10-30', 'evento': 'Eleições Presidenciais (2º Turno)', 'posicao_y': 5.4},
        {'data': '2023-04-01', 'evento': 'Apresentação do Arcabouço Fiscal', 'posicao_y': 4.95}
    ]

    # Corrige o índice para usar como eixo X
    dados_dolar = dados_dolar.reset_index()

    # Cria o gráfico
    fig = px.line(
        dados_dolar,
        x='Date',
        y='Cotação',
        title='Cotação do Dólar (USD para BRL) ao Longo do Tempo',
        labels={'Date': 'Data', 'Cotação': 'Valor em R$'}
    )

    # Adiciona eventos históricos ao gráfico
    for evento in eventos:
        fig.add_vline(x=evento['data'], line_width=1, line_dash="dash", line_color="red")
        fig.add_annotation(
            x=evento['data'], y=evento['posicao_y'], text=evento['evento'],
            showarrow=True, arrowhead=2, ax=0, ay=-40,
            bordercolor="#c7c7c7", borderwidth=1, borderpad=4,
            bgcolor="#ff7f0e", opacity=0.8
        )

    fig.update_layout(
        xaxis_title="Data",
        yaxis_title="Cotação (R$)",
        font=dict(family="Arial, sans-serif", size=12, color="#333"),
        hovermode="x unified"
    )

    st.plotly_chart(fig, use_container_width=True)

    # --- 5. Detalhamento dos Eventos ---
    st.header("Entenda os Eventos Marcados")
    st.markdown("Clique em cada evento para saber mais sobre o contexto da época.")
    for evento in sorted(eventos, key=lambda e: e['data']):
        data_formatada = pd.to_datetime(evento['data']).strftime('%d/%m/%Y')
        with st.expander(f"🗓️ **{data_formatada}**: {evento['evento']}"):
            if evento['evento'] == 'Impeachment de Dilma Rousseff':
                st.write("O processo de impeachment gerou grande instabilidade política e econômica...")
            elif evento['evento'] == 'Greve dos Caminhoneiros':
                st.write("A paralisação de 11 dias causou uma crise de abastecimento...")
            elif evento['evento'] == 'OMS declara pandemia de COVID-19':
                st.write("O início da crise sanitária global provocou uma corrida mundial por dólares...")
            elif evento['evento'] == 'Pico do Dólar (Pandemia)':
                st.write("Em meio ao auge das incertezas da pandemia e ruídos políticos internos...")
            elif evento['evento'] == 'Início do ciclo de alta da inflação':
                st.write("A inflação persistente no Brasil e no mundo levou o Banco Central...")
            elif evento['evento'] == 'Início da Guerra na Ucrânia':
                st.write("O conflito aumentou os preços das commodities...")
            elif evento['evento'] == 'Eleições Presidenciais (2º Turno)':
                st.write("Períodos eleitorais são marcados por alta volatilidade...")
            elif evento['evento'] == 'Apresentação do Arcabouço Fiscal':
                st.write("A proposta de uma nova regra para controlar as contas públicas...")

# --- 6. Rodapé ---
st.markdown("---")
st.info
